/* $Id: LatLongPtsT.h,v 1.1.1.1 2001-01-29 08:20:25 paklein Exp $ */
/* created: paklein (10/31/1997)                                          */
/* Base class for spherical point generators.                             */

#ifndef _LATLONG_PTS_T_H_
#define _LATLONG_PTS_T_H_

/* base class */
#include "SpherePointsT.h"

/* forward declarations */
class ifstreamT;

class LatLongPtsT: public SpherePointsT
{
public:

	/*
	 * Constructor
	 */
	LatLongPtsT(ifstreamT& in);

	/*
	 * Print parameters.
	 */
	virtual void Print(ostream& out) const;
	virtual void PrintName(ostream& out) const;	

	/*
	 * Generate sphere points:
	 *
	 *   phi   = angle about z from x
	 *   theta = angle about x from z
	 *
	 * The final orientation is generated by applied the
	 * phi and theta rotations in succession about the local
	 * axes.
	 *
	 */
	virtual const dArray2DT& SpherePoints(double phi, double theta);

private:

	/* parameters */
	int	fNphi;
	int fNtheta;
			
};

#endif /* _LATLONG_PTS_T_H_ */
