#!/usr/bin/perl -w
# $Id: tahoe-manager,v 1.32 2005-03-09 09:25:55 paklein Exp $
#------------------------------------------------------------------------------
# tahoe-manager: 
#    a PERL script to checkout, configure, build and run regression tests
#    for TAHOE
# written by: 
#    Reese Jones (rjones@sandia.gov) and Patrick Klein (paklein@sandia.gov)
#------------------------------------------------------------------------------

use Cwd; # $home = cwd();

# prefix on macros in the makefiles
%module2define = qw(
expat	EXPAT_
toolbox	TB_
tahoe	TAHOE_
macros	NODEFINE
spooles SPOOLES_
spoolesMPI SPOOLESMPI_
metis   METIS_
aztec   AZ_
f2c	    F2C_
CBLAS	BLAS_
access	AX_
development DEV_
Sierra SIERRA_
qhull  QHULL_
contrib NODEFINE
benchmark_XML NODEFINE
);

# location of module on the server
%module2repo = qw(
expat /cvs/protected/tahoe
toolbox /cvs/protected/tahoe
tahoe /cvs/protected/tahoe
macros /cvs/protected/tahoe
spooles /cvs/protected/tahoe
spoolesMPI /cvs/protected/tahoe
metis /cvs/protected/tahoe
aztec /cvs/protected/tahoe
f2c /cvs/protected/tahoe
CBLAS /cvs/protected/tahoe
access /cvs/protected/tahoe
development /cvs/private/tahoe
Sierra /cvs/private/tahoe
qhull /cvs/private/tahoe
benchmark_XML /cvs/protected/tahoe
contrib /cvs/protected/tahoe
);

# "touch" targets
%module2touch = qw(
spooles touch_spooles
spoolesMPI touch_spooles
aztec touch_Aztec
f2c touch_f2c
access touch_SEACAS
metis touch_METIS
);

# modules in the UP_TO_DATE macro
%up_to_date_modules = qw(
development 1
Sierra 1
);

# modules available via http
%http_modules = qw(
macros 1
expat 1
toolbox 1
tahoe 1
benchmark_XML 1
metis 1
spooles 1
spoolesMPI 1
spoolesMT 1
contrib 1
benchmark_XML 1
);

# minimum required installation
@defaultmodules = ("macros","expat","toolbox","tahoe");

%syslib2module = qw(
ACCESS	access
);

%module2syslib = qw(
access ACCESS
);

%connect2command = qw(
cvs     cvs
http	curl
);

# tahoe server
$ tahoe = "tahoe.ca.sandia.gov"; 

# default configuration file
$config_file = "./.tahoe_config";

# initialization
$count = 0;
initialize();

# loop through arguments and options
$script_status = 0;
if (@ARGV < 1) {usage(); exit 0;}
ARG: while (@ARGV) {
	OPT: for (shift@ARGV) {
		$count = @ARGV;
		if ($script_status > 0 )   { failed();}
		if (/^u|update/i)          { update(); next ARG; }
		if (/^co|config/i)          { config(); next ARG; }
		if (/^i|init/i)            { init(); next ARG; }
		if (/^b|build/i)           { build(); next ARG; }
		if (/^cl|clean/i)          { clean(); next ARG; }
		if (/^t|test/i)            { test(); next ARG; }
		if (/^u|usage|help|^h/i)   { usage();}
		if (/^s|selfupdate/i)   { selfupdate(); exit 0; }
		print "ERROR: unknown option: $_ \n"; usage();
	}
}

exit 0;

###############################################################################
sub selfupdate {
	if ($connection =~ /cvs/) {
		print "updating...\n";
		system("cvs -q update tahoe-manager");
	} else {
		print "no selfupdate for connection $connection\n";
	}
}

###############################################################################
sub initialize {

# classify modules
my @allmodules = sort(keys(%module2define));
@optionalmodules = complement(\@allmodules, \@defaultmodules);

# search for system libs 
foreach my $key (sort(keys %ENV)) {
	foreach my $lib (keys %syslib2module) {
		if ($key =~ /$lib/ ) { 
			my $loc = $ENV{$key};
			print "* found system library $lib \@ $loc \n"; 
			push(@syslibs,$lib);
		}
	}
}

# configuration file
if(-e "$config_file") { read_config();}
else                  { write_default_config();}

# remove system libraries from @modules
foreach my $lib (@syslibs) {
	for (my $i = 0; $i < scalar(@modules) ; $i++) {
		if($modules[$i] =~ /^$syslib2module{$lib}$/) {  splice (@modules,$i,1);}
	}
}

# check for missing required modules
my @req_missing = get_missing_modules();
while (scalar(@req_missing) > 0) {
	print "adding required modules: @req_missing\n";
	foreach my $mod (@req_missing) {
		push(@modules, $mod);
	}
	write_config();
	@req_missing = get_missing_modules();
}

print ">   tahoe name: $tahoe_name\n";
print ">   connection: $connection\n";
if ($proxy !~ "NONE") {
	print ">        proxy: $proxy\n";
}
print "> architecture: $arch \n\n"; 

# check connection method
#open(WHICH, "which $connect2command{$connection} |");
if (my_which($connect2command{$connection}) =~ "") {
	print "ERROR: command \"$connect2command{$connection}\" not found\n";
	if ($connection =~ "http") {
		print "ERROR: curl is available from http://curl.haxx.se/\n";
	}
 	exit;
}

# check cvs settings
if ($connection =~ "cvs") {
	my $cvs_OK = 0;
	foreach my $key (sort(keys %ENV)) {
		if ($key =~ "CVS_RSH" && $ENV{$key} =~ "ssh") { $cvs_OK = 1; }
	}
	if ($cvs_OK != 1) {
		print "ERROR: CVS_RSH must be set to ssh\n";
		exit;
	}
}
}

##############################################################################
sub config {
	@config_options = ("add optional modules", "remove optional modules", "configure options within modules");

	my @mods = @modules;
	print "\n> installed modules: @mods\n";
	print "configuration options:\n";
	my $i = 0;
	foreach my $option (@config_options) {
		print "$i $option\n"; 
		$i++
	}
	
	my $change = 0;
	print "\nchoice: ";
	my $choice = <STDIN>;
	if ($choice =~ /0/) {
		$change = add_optional_modules();
		write_config();
	} elsif ($choice =~ /1/) {
		$change = remove_optional_modules();
		write_config();
	} else {
		$change = module_config();
	}
	
	# rewrite configuration file
	write_config();
	print "\n* changes won't take effect until next build\n\n" if ($change > 0);
}

##############################################################################
sub read_config{
print "* reading config file $config_file\n";
open(CONFIG,$config_file) || die "cannot open file $config_file for reading : $!";
my $type = "UNKNOWN";
while(<CONFIG>) {
	s/^\s+//; s/\s+$//; @list = split(/ +/);
 	if (defined($list[0])){
        	if (/^\#/ ){ 
			if ($type  =~ /CONNECTION/) {$connection = $tmp_list[0];}
			elsif ($type =~ /TAHOE_LOGIN/) { $tahoe_name = $tmp_list[0]; }
			elsif  ($type  =~ /PROXY/){$proxy = $tmp_list[0];}
			elsif  ($type  =~ /ARCH/){$arch = $tmp_list[0];}
			elsif  ($type  =~ /USE_DEFAULT/){$use_default_arch = $tmp_list[0];}
			elsif  ($type  =~ /VERBOSE/){ $verbose = $tmp_list[0]; }
 			elsif  ($type  =~ /MODU/){@modules = @tmp_list;}
 			$type = $list[1]; @tmp_list =();
 		} 
 		else { push(@tmp_list,@list);}
 	}
}
close(CONFIG);

# need to make sure the core modules exist
my @missing_core = complement(\@defaultmodules, \@modules);
if (scalar(@missing_core) > 0) {
	print "* adding : @missing_core to modules\n" ; 
	foreach my $mod (@missing_core) {
		push (@modules, $mod);
	}
	write_config();
}
}

##############################################################################
sub write_default_config{
print "* creating default config file $config_file\n";

# look for environmental settings
my $cvs_rsh;
$verbose = "false";
$use_default_arch = "true";
$tahoe_name = "nobody";
foreach my $key (sort(keys %ENV)) {
	my $value =  $ENV{$key};
	if ($key =~ "TAHOE_CONNECT" ) {
		print "* found environmental var : $key = $value\n";
		$connection = $value;}
	if ($key =~ "TAHOE_ARCH") { 
		print "* found environmental var : $key = $value\n";
		$arch = $value; }
	if ($key =~ "CVS_RSH") { 
		print "* found CVS_RSH env var, using cvs connection\n"; 
		$cvs_rsh = $value; }
	
	# get user name on local machine
	if ($key =~ /^USER$/) {
		$tahoe_name = $value;
		# the builtin function getlogin() sometimes returns the wrong name
	}
}

# connection type
$proxy = "NONE";
unless(defined($connection)) { 
	@connections = ("cvs", "http");
	my $i=0;
	foreach my $choice (@connections) { 
		print "$i $choice\n"; 
		$i++; 
	}
	my $connect_default = 1;
	$connect_default = 0 if (defined($cvs_rsh));
	print "connection type [$connect_default]: ";
	$i = <STDIN>; 
	chomp($i);
	if (length($i) == 0) { # default
		$i = $connect_default;
	}
	$connection = $connections[$i];
	if ($connection =~ "http") { # ask for proxy
		print "http proxy (proxyhost:port) [NONE]:";
		$proxy = <STDIN>;
		chomp($proxy);
		if (length($proxy) == 0) { # default
			$proxy = "NONE";
		}
	}
	else {
        my $cvs_OK = 0;
        foreach $key (sort(keys %ENV)) {
                if ($key =~ "CVS_RSH" && $ENV{$key} =~ "ssh") { $cvs_OK = 1; }
        }
        if ($cvs_OK != 1) {
                print "ERROR: CVS_RSH must be set to ssh\n";
                exit;
        }
	}
}

# Tahoe server login name
if ($connection =~ "cvs") {
	print "Tahoe server username [$tahoe_name]: ";
	my $name = <STDIN>; chomp($name);
	if (length($name) > 0) {
		$tahoe_name = $name;
	}
}

# get macros module
unless(-d "macros") {
	if ($connection =~ "cvs") {
		print "checking out macros...";
		update("macros");
		print " ok\n";
	} elsif ($connection =~ "http") {
	
		# grab new copy
		my $curl_cmd = "curl http://tahoe.ca.sandia.gov/download/nightly/macros.tar.gz --remote-name --connect-timeout 10";
		if ($proxy !~ "NONE") {
			$curl_cmd = $curl_cmd." --proxy $proxy";
		}
		system("$curl_cmd") == 0
			or die "ERROR: curl failed. Check connection or proxy ($proxy)";

		# unpack
		system("gunzip macros.tar.gz");
		system("tar xf macros.tar");
		system("rm macros.tar");
	}
	else {
		print "ERROR: unrecognized connection '$connection'\n";	
		exit;
	}
}

# architecture
$arch = get_arch() unless(defined($arch));
print "do want this to be the default architecture for all modules (y/n) [y]: "; 
$use_default_arch = "true";
$choice = <STDIN>;
if ( $choice =~ /n/ ) { $use_default_arch = "false"; }

# modules
@modules = @defaultmodules;
my $choice = 0;
foreach my $key (sort(keys %ENV)) {
	if ($key =~ /TAHOE_BUILD/ && $ENV{$key} =~ /default/) { $choice = 1; }
}
if ($choice != 1) {
	print "* default modules : @defaultmodules\n";

	# add optional modules
	print "do want to add optional modules (y/n) [n]: "; 
	$choice = <STDIN>;
	if ( $choice =~ /y/ ) {
		add_optional_modules();
	}
}
print "\n";

# write configuration file
write_config();
}

##############################################################################
sub update{

	# run all unless specified
	my @run_modules = @_;
	if (scalar(@run_modules) == 0) {
		@run_modules = @modules;
	}

	$time = localtime();
	print "($count) updating: @run_modules, at $time\n";

	# connection type
	if ($connection =~ "cvs") {
		update_cvs(@run_modules);
	} elsif ($connection =~ "http") {
		update_http(@run_modules);	
	}
	else {
		print "ERROR: unrecognized connection '$connection'\n";	
		exit;
	}
}

##############################################################################
sub update_cvs {

	# run all unless specified
	my @run_modules = @_;
	if (scalar(@run_modules) == 0) {
		@run_modules = @modules;
	}

	unlink("cvs.log");
	foreach my $dir (@run_modules) {

		next if defined($module2syslib{$dir});

		if (-d $dir) {
			print "\tupdating $dir...";
			chdir($dir);
			#system("cvs update -Pd > ../cvs.log 2>&1");
			system("cvs -q update -Pd > ../cvs.log");
			chdir("..");
		} else {
			print "\tchecking out $dir...";
			my $repo = $module2repo{$dir};
			#system("cvs -d $tahoe_name\@$tahoe:$repo checkout $dir > cvs.log 2>&1");
			system("cvs -d $tahoe_name\@$tahoe:$repo -q checkout $dir > cvs.log");
		}
		# check for failures
		my ($errors, $patches, $updates, $merges) = (0, 0, 0, 0);
		open(IN,"cvs.log");
		my $first_line = 0;
		while (defined(my $line = <IN>)) {
			my $hit = 0;
			if ($line =~ /^C /) {
				$errors++;
				$hit = 1 if ($verbose =~ /true/i);
			}
			if ($line =~ /^P /) {
				$patches++;
				$hit = 1 if ($verbose =~ /true/i);
			}
			if ($line =~ /^U /) {
				$updates++;
				$hit = 1 if ($verbose =~ /true/i);
			}
			if ($line =~ /^M /) {
				$merges++;			
				$hit = 1 if ($verbose =~ /true/i);
			}
			
			# write it
			if ($hit == 1) {
				if ($first_line == 0) {
					print "\n";
					$first_line = 1;
				}
				print $line;
			}
		}
		print "\t... " if ($first_line > 0);
		print " {U($updates), M($merges), P($patches), C($errors)}";
		if ($errors > 0) {
			$script_status++;
			print " conflicts found\n";
		} else {
			print " ok\n";
		}
		
		# mark for init
		if (-d $dir && 
			$errors + $patches + $updates + $merges > 0 && 
			$module2define{$dir} !~ "NODEFINE") {
			system("echo 'init' > $dir/.status");
		}
	}
}

##############################################################################
sub update_http {

	# run all unless specified
	my @run_modules = @_;
	if (scalar(@run_modules) == 0) {
		@run_modules = @modules;
	}

	foreach $dir (@run_modules) {
	
		# check
		if (!defined($http_modules{$dir})) {
			print "ERROR: module $dir is not available via http\n";
			exit;
		}
	
		print "\tupdating $dir...\n";
		
		# grab new copy
		my $curl_cmd = "curl http://tahoe.ca.sandia.gov/download/nightly/$dir.tar.gz --remote-name --connect-timeout 10";
		if ($proxy !~ "NONE") {
			$curl_cmd = $curl_cmd." --proxy $proxy";
		}
		system("$curl_cmd") == 0
			or die "ERROR: curl failed. Check connection or proxy ($proxy)";

		# move existing directory aside
		if (-d $dir) {

			# parse the date
			my ($sec, $min, $hour, $mday, $mon, $year, , , ) = localtime;
			my $the_date = sprintf("%02d%02d%04d-%02d:%02d:%02d", $mon+1, $mday, $year+1900, $hour, $min, $sec);

			# rename
			if (! -d "saved") {
				system("mkdir saved");
			}
			system("mv $dir saved/$dir.$the_date");
		} 
			
		# unpack
		system("gunzip $dir.tar.gz");
		system("tar xf $dir.tar");
		if ($module2define{$dir} !~ "NODEFINE") {
			system("echo 'init' > $dir/.status");
		}
		
		# clean up
		system("rm $dir.tar");
		print " ok\n";
	}
}

##############################################################################
sub build {

	# run all unless specified
	my @run_modules = @_;
	if (scalar(@run_modules) == 0) {
		@run_modules = @modules;
	}

	$time = localtime();

	# initialize modules if needed
	my @init_modules = ();
	my $tahoe_added = 0;
	my $add_tahoe = 0;
	foreach my $dir (@run_modules) {
		my $add = 0;
		if (! -e $dir) { $add = 1; }
		elsif (! -e "$dir/makefile" && -e "$dir/makefile.template")  { $add = 1; }
		elsif (-e "$dir/.status") { 
			$add = 1; 
			
			# update tahoe
			$add_tahoe = 1 if defined($up_to_date_modules{$dir});
		}
		
		# adding tahoe
		$tahoe_added = 1 if ($add > 0 && $dir =~ "tahoe");
		
		# needs init
		push(@init_modules, $dir) if ($add > 0);
	}
	push(@init_modules, "tahoe") if ($add_tahoe > 0 && $tahoe_added == 0);
	init(@init_modules) if (scalar(@init_modules) > 0);

	# need to sort modules based on dependencies
	my @tmp_modules = sort_by_depend(@run_modules);
	if (scalar(@tmp_modules) > 1 )  {
		print "($count) building: @tmp_modules, at $time\n";}

	DIR: foreach my $dir (@tmp_modules) {
		if (-e "$dir/makefile" && !defined($up_to_date_modules{$dir})) {

			chdir($dir);
			print "\tmaking $dir...";
			system("make build > build.log 2>&1");
			
			# check for errors	
			open(IN,"build.log");
			my @lines = <IN>; $file = "@lines"; close(IN); 
			my $errors = ($file =~ /\*\*\* ERROR:/);
               		if($errors > 0) {
               			print " ERROR\n";
               			$script_status++;
               		}
			else { print " ok\n"; }
			chdir "..";
		}
	}
}

##############################################################################
sub init {

	# run all unless specified
	my @run_modules = @_;
	if (scalar(@run_modules) == 0) {
		@run_modules = @modules;
	}

	$time = localtime();

	# confirm all modules are checked out
	foreach my $dir (@run_modules) {
		if (! -e $dir) { update($dir); }
	}

	# update makefiles in each module - do all at once before entering loop below
	# since this may be interactive
	foreach my $dir (@run_modules) {
		if (-e $dir) { 
			chdir $dir; 
			if (-e "makefile.template") {

				# generate makefile
				print "\tcreating makefile in $dir...";
				fillin_makefile();
				print " ok\n";
			}
			chdir ".."; 
		}
	}
	
	# need to sort modules based on dependencies
	my @tmp_modules = sort_by_depend(@run_modules);
	print "($count) initializing: @tmp_modules, at $time\n";	

	foreach my $dir (@tmp_modules) {
		if (-e $dir) { 
			chdir $dir; 
			if (-e "makefile.template") {

				# run "make init"
				if (!defined($up_to_date_modules{$dir})) {
					print "\tinitializing $dir...";
					system("make init > init.log 2>&1");
					
					# check for errors	
					open(IN,"init.log");
					my @lines = <IN>; $file = "@lines"; close(IN); 
					my $errors = ($file =~ /\*\*\* ERROR:/);
               		if($errors > 0) {
               			print " ERROR\n";
               			$script_status++;
               		}
					else { 
						print " ok\n"; 
						unlink(".status"); # remove flag
					}
				} else { unlink(".status"); } # remove flag
			}
		 	chdir "..";
		}
	}
}

##############################################################################
sub clean {

	# run all unless specified
	my @run_modules = @_;
	if (scalar(@run_modules) == 0) {
		@run_modules = @modules;
	}

	$time = localtime();
	print "($count) cleaning: @modules, at $time\n";
	foreach $dir (@run_modules) {
		if (-e $dir) { 
			chdir $dir; 
			if (-e "makefile") {
				print "\tcleaning $dir...";
				system("make clean > clean.log 2>&1");
				print " ok\n";
				
				# remove the makefile
				unlink("makefile");
		
				# remove flag
				unlink(".built");
		
				# flag
				system("echo 'init' > .status");
			}
		 	chdir "..";
		}
	}

}

##############################################################################
sub test{
	$time = localtime();
	print "($count) running tests at $time\n";
 	unless(-d "benchmark_XML"){
		print "checking out benchmark\n";
		unlink("cvs.log");
		my $repo = $module2repo{"benchmark_XML"};
		system("cvs -d $tahoe_name\@$tahoe:$repo checkout benchmark_XML > cvs.log 2>&1");
 	} else {
		system("cd benchmark_XML; cvs -q update -Pd > cvs.log 2>&1");
	}
	chdir("benchmark_XML/comparator");
	print("\tbuilding comparator...");
	fillin_makefile(); system("make init build > build.log 2>&1");
	print(" ok\n");
	chdir("..");
	print("\trunning benchmarks");
	print("\tremoving previous results...");
	system("make clean > build.log 2>&1");
	print(" ok\n");
	print("\trunning benchmark cases...");
	system("../tahoe/tahoe -f run.batch > run.out 2>&1");
	print(" ok\n");
	print("\tcomparing benchmarks...");
	system("./comparator/compare -f run.batch > compare.out 2>&1");
	print(" ok\n");
	open(IN,"compare.summary");
	<IN>; 
	$_ = <IN>; chomp(); s/^\s+//; s/\s+$//; $pass = $_;   
	$_ = <IN>; chomp(); s/^\s+//; s/\s+$//; $fail = $_;   
	print "* $pass,  $fail, see compare.summary for more details\n";
}

##############################################################################
sub failed{
	$time = localtime();
	die "*-*-*-* process FAILED at $time *-*-*-*\n";
}

##############################################################################
sub usage {
	print "\nusage: tahoe-manager [list options]\n";
	print "       build   : builds modules (calls init if needed)\n";
	print "       config  : change build options\n";
	print "       update  : updates or checks out modules\n";
	print "   selfupdate  : updates this script\n";
	print "       init    : creates makefiles and initializes modules\n";
	print "       clean   : cleans modules\n";
	print "       test    : runs regression tests\n";
	print "\n";
	exit 1;
}

##############################################################################
sub a_depends_on_b {

	# needs two arguments
	if (scalar(@_) != 2) {
		print "a_depends_on_b: expecting 2 arguments\n";
	}
	my ($a, $b) = @_;

	# look for dependency in makefile
	my $source = "$a/makefile.template";
	if (-e $source) {
		open(IN, "$source");
		my @lines = <IN>; $afile = "@lines"; 
		close(IN);
		my $bdefine = $module2define{$b}; 
 		my $a_on_b = ($afile =~ /$bdefine/);
		if ($a_on_b > 0) { return 1; }
	}
	return 0;
}

##############################################################################
sub by_depend {

	my $filename = "$a/makefile.template";
	my $a_on_b = -1;
	if (-e $filename) {
		open(IN,"$filename");
		my @lines = <IN>; $afile = "@lines"; 
		close(IN);
		my $bdefine = $module2define{$b}; 
 		$a_on_b = ($afile =~ /$bdefine/);
		unless($a_on_b > 0) {$a_on_b = 0;}
	}

	$filename = "$b/makefile.template";
	my $b_on_a = -1;
	if (-e $filename) {
		open(IN,"$filename");
		my @lines = <IN>; $bfile = "@lines"; 
		close(IN);
		my $adefine = $module2define{$a};
		$b_on_a = ($bfile =~ /$adefine/);
		unless($b_on_a > 0) {$b_on_a = 0;}
	}

	# bi-directional dependency with tahoe => tahoe goes last
	if ($a_on_b == $b_on_a && ($a =~ "tahoe" || $b =~ "tahoe") ) {
		if ($a =~ "tahoe") {
			$a_on_b = $b_on_a + 1;
		} else {
			$b_on_a = $a_on_b + 1;
		}
	}

	#print " $a $a_on_b $b $b_on_a \n";

	($a_on_b <=> $b_on_a);
}

##############################################################################
sub fillin_makefile{

	# no config file in this module
	my $mod_arch = $arch;	
	if (! -e ".tahoe_config") {
		if( $use_default_arch =~ /false/i ) {
		print " use default ARCH = $mod_arch (y/n) [y]: ";
		$ans = <STDIN>;
		chomp($ans);
		if (length($ans) > 0 && $ans !~ /y/i) {
			my $path = cwd();
			chdir("..");
			$mod_arch = get_arch();
			chdir($path);
		}
		}
		print "...";

		# write module config file
		open (ARCH, ">.tahoe_config") || die "could not open .tahoe_config\n";
		print ARCH "$mod_arch\n";
		close (ARCH);
	}
	
	# read the arch 
	open (ARCH, ".tahoe_config") || die "could not open .tahoe_config\n";
	$mod_arch = <ARCH>;
	close(ARCH);
	chomp($mod_arch);

	# if makefile exists, preserve MOD_ macros in makefile
	my %mod_macros = qw(
		MOD_CFLAGS_C 0
		MOD_CFLAGS_CC 0
		MOD_CFLAGS_F 0
		MOD_LFLAGS 0
	);
	my @mod_macros_keys = ();
	if (-e "makefile") {
		open(IN, "makefile");
		@mod_macros_keys = keys(%mod_macros);
		while (defined($line = <IN>)) {
			foreach my $key (@mod_macros_keys) {
				if ($line =~ /$key\s*=/) {
					$mod_macros{$key} = $line;
				}
			}
		}
		close (IN);
	}

	unlink("makefile");
	my $path = cwd();
	open(IN,"makefile.template");
	open(OUT,">makefile");
	print OUT "################################################################################\n";
	print OUT "#### NOTE: This makefile is automatically generated from makefile.template. ####\n";
	print OUT "####       Changes to the MOD_ macros are preserved. All other changes will ####\n";
	print OUT "####       be lost.                                                         ####\n";
	print OUT "################################################################################\n\n";
	while (defined(my $line = <IN>)){
	
		# configuration
		$line =~ s/^HOME_DIR =/HOME_DIR = $path/;
		$line =~ s/^ARCH =/ARCH = $mod_arch/;
		
		# restore MOD_ macros
		foreach my $key (@mod_macros_keys) {
			if ($line =~ /$key\s*=/) {
				$line = $mod_macros{$key};
			}
		}
		
		# optional modules
		foreach my $module (@modules) {
			my $define = $module2define{$module};
			$line =~ s/\#$define/$define/;
		}
		foreach my $syslib (@syslibs) {
			my $define = $module2define{$syslib2module{$syslib}};
			$line =~ s/\#$define/$define/;
		}
		
		# UP_TO_DATE modules - tahoe module only
		if ($path =~ /tahoe-install\/tahoe/ && $line =~ /UP_TO_DATE\ =\ NONE/) {
			$up_to_date = "";
			foreach $module (@modules) {
				if (defined($up_to_date_modules{$module})) {
					$up_to_date = $up_to_date." \$(".$module2define{$module}."DIR)";
				}
			}
			if (length($up_to_date) > 0) {
				$line =~ s/=\ NONE/=$up_to_date/;
			}
		}
		
		print OUT "$line";
 	}
	close(IN);
	close(OUT);
}

##############################################################################
sub my_which{
	my $cmd = shift(@_); 
        my $location = "";
        my @paths= split(":",$ENV{"PATH"});
        foreach my $path (@paths) {
                if (-x "$path/$cmd") { $location = $path; last;}
        }
        return $location;
}

##############################################################################
sub write_config {
	open(CONFIG,">$config_file") || die "cannot open file $config_file for writing : $!";
	print CONFIG  "# TAHOE_LOGIN\n$tahoe_name\n\n";
	print CONFIG  "# CONNECTION\n$connection\n\n";
	print CONFIG  "# PROXY\n$proxy\n\n";
	print CONFIG  "# ARCHITECTURE\n$arch\n\n";
	print CONFIG  "# USE_DEFAULT\n$use_default_arch\n\n";
	print CONFIG  "# MODULES\n@modules\n\n";
	print CONFIG  "# VERBOSE\n$verbose\n\n";
	print CONFIG  "# EOF";
	close(CONFIG);
}

##############################################################################
sub add_optional_modules {

	# collect optional modules not currently included
	my @newoptionalmodules = complement(\@optionalmodules, \@modules);	
	if (scalar(@newoptionalmodules) == 0) {
		print "\n* all optional modules already included\n\n";
		return 0;
	}

	# select modules to add
	print "\noptional modules:\n";
	my $i = 0;
	foreach my $choice (@newoptionalmodules) { 
		print "$i $choice\n"; 
		$i++;
	}
	print "\nmodule numbers to add: "; 
	my $choice = <STDIN>; 
	chomp($choice);
	my @choices = split(/ +|,/,$choice);
	my @addmodules = ();
	foreach my $choice (@choices) {
		$choice = $newoptionalmodules[$choice];
		push (@addmodules, $choice);
		push (@modules, $choice);
		update ($choice) if (! -d $choice);
	}

	# look for other modules that must/may be included
	my $done = 0;
	while ($done == 0) {

		# add any additional required modules
		my @missing_required = get_missing_modules();
		if (scalar(@missing_required) > 0) {
			print "adding required modules: @missing_required\n";
			foreach my $mod (@missing_required) {
				push(@addmodule, $mod);
				push(@modules, $mod);
				update($mod) if (! -d $mod); # fetch new modules to determine dependencies
			}
			@newoptionalmodules = complement(\@optionalmodules, \@modules);
		}
	
		# optional modules not included
		my @missingmodules = complement(\@newoptionalmodules, \@addmodules);
		my @dependmodules = ();
		foreach $missingmodule (@missingmodules) { # missing module needed due to dependency
			DEP: foreach $addmodule (@addmodules) {
				if (a_depends_on_b($addmodule, $missingmodule) == 1) {
					push (@dependmodules, $missingmodule);
					last DEP;
				}
			}
		}

		# add dependent modules
		if (scalar(@dependmodules) > 0) {
			print "the newly added modules can be extended with optional modules: @dependmodules\n";
			print "add optional modules (y/n) [y]: ";
			my $ans = <STDIN>;
			if ($ans !~ /n/i) {
				foreach $module (@dependmodules) {
					push (@addmodules, $module);
					push (@modules, $module);
					update($module) if (! -d $module); # fetch new modules to determine dependencies
				}
				@newoptionalmodules = complement(\@optionalmodules, \@modules);
			} else { $done = 1; }
		} else { $done = 1; }
	}	

	# flag modules that need to be re-initialized
	foreach my $module (@modules) {
		foreach my $addmodule (@addmodules) {
			if (a_depends_on_b($module, $addmodule) == 1) {
				system("echo 'init' > $module/.status");
			}
			
			# "touch" target
			if (-e "$module/makefile" && defined($module2touch{$addmodule})) {
				chdir($module);
				system("make $module2touch{$addmodule} >> build.log 2>&1");
				chdir("..");
			}
		}
	}

	print "* modules : @modules \n";
	return 1;
}

##############################################################################
sub remove_optional_modules {

	# collect optional modules currently included
	my @curr_optionalmodules = intersection(\@optionalmodules, \@modules);
	if (scalar(@curr_optionalmodules) == 0) {
		print "\n* no optional modules included\n\n";
		return 0;
	}
	
	# select modules to remove
	print "\noptional modules:\n";
	my $i=0;
	foreach my $choice (@curr_optionalmodules) { 
		print "$i $choice\n"; 
		$i++;
	}
	print "\nmodule numbers to remove: "; 
	$choice = <STDIN>; 
	chomp($choice);
	my @choices = split(/ +|,/,$choice);

	# flag modules that need to be re-initialized
	foreach my $module (@modules) {
		foreach $choice (@choices) {
			my $outmodule = $curr_optionalmodules[$choice];
			if (a_depends_on_b($module, $outmodule) == 1) {
				system("echo 'init' > $module/.status");
			}

			# "touch" target
			if (-e "$module/makefile" && defined($module2touch{$outmodule})) {
				chdir($module);
				system("make $module2touch{$outmodule} >> build.log 2>&1");
				chdir("..");
			}
		}
	}

	# rebuild modules list
	foreach $choice (@choices) {
		my @modules_tmp = @modules;
		@modules = ();
		foreach $module (@modules_tmp) {
			if ($module !~ /^$curr_optionalmodules[$choice]$/) {
				push(@modules, $module);
			}
		}
	}
	print "* modules : @modules \n";
	return 1;
}

##############################################################################
sub module_config {

	# collect list of configurable modules
	my @config_modules = ();
	foreach my $module (@modules) {
		if (-d "$module/config") {
			open(CHECK, "ls -1 $module/config | grep -c \.conf |");
			my $count = <CHECK>;
			chomp($count);
			close(CHECK);
			if ($count > 0) {
				push(@config_modules, $module);
			}
		}
	}
	
	if (scalar(@config_modules) == 0) {
		print "* there are no modules with configurable options\n\n";
		return 0;
	}
	else {
		print "\nconfigurable modules:\n";
		my $i=0;
		foreach my $choice (@config_modules) { 
			print "$i $choice\n"; 
			$i++;
		}
		my $change = 0;
		print "\nmodules to configure: ";
		$choice = <STDIN>; 
		chomp($choice);				
		my @choices = split(/ +|,/,$choice);
		foreach $choice (@choices) {	
			$change += configure_module($config_modules[$choice]);
		}
		return $change;
	}
}

##############################################################################
sub configure_module {
	my $module = shift(@_);
	
	# regenerate the configuration headers
	chdir $module;
	fillin_makefile();
	system("make update_config > build.log 2>&1");
	
	# find configuration headers
	@config_headers = ();
	open(LS, "ls -1 src-mirror/config |");
	while (defined($file = <LS>)) {
		chomp($file);
		if ($file =~ /\.h$/) {
			push(@config_headers, $file);
		}
	}

	my $change = 0;
	if (scalar(@config_headers) == 0) {
		print "\n* there are no headers with configurable options\n\n";	
	} else {
		print "\nconfigurable headers in module $module:\n";
		$i=0;
		foreach my $choice (@config_headers) { 
			print "$i $choice\n"; 
			$i++;
		}	print "\nheaders to configure: ";
		$choice = <STDIN>; 
		chomp($choice);
		my @choices = split(/ +|,/,$choice);
		foreach $choice (@choices) {	
			if (configure_header($config_headers[$choice]) != 0) {
				system("echo 'init' > .status");
				$change++;
			}
		}
	}

	# up
	chdir "..";
	return $change;
}

##############################################################################
sub configure_header {
	my $header = shift(@_);
	
	# read header info
	my @info = ();
	my @status = ();
	my @symbol = ();
	open(IN, "src-mirror/config/$header") || die "could not open \"$header\"\n";
	my $flag = 0;
	my $max_len = 0;
	while (defined(my $line = <IN>)) {
		if ($flag == 0) {
			$flag = 1 if ($line =~ /\\def [a-zA-Z0-9_-]/);
		} elsif ($flag == 1) { # description
			chomp($line);
			$line =~ s/( \* )(.*)/$2/;
			push(@info, $line);
			$flag = 2;
		} elsif ($flag == 2) {

			# forward to #define line			
			while ($line !~ /^[\/\* ]*#define/) { $line = <IN>; }
		
			# status
			chomp($line);
			if ($line =~ /^#define/) {
				push(@status, " ON");
			} else {
				push(@status, "OFF");			
			}
			
			# symbol
			$line =~ s/(.*#define )([a-zA-Z0-9_-]+)(.*)/$2/;
			push(@symbol, $line);
			$max_len = length($line) if (length($line) > $max_len);
			$flag = 0;
		}
	
	}
	close(IN);

	# prompt for changes
	my @oldstatus = @status;
	my $done = 0;
	while ($done == 0) {
		print "\nOptions:\n";
		my $i = 0;
		while ($i < scalar(@symbol)) {
			print " " if ($i < 10);
			my $line = "$i $status[$i] $symbol[$i]";
			my $j = 0;
			while ($j < $max_len - length($symbol[$i])) {
				$line = $line." ";
				$j++;
			}
			$line = $line." $info[$i]\n";
			print $line;
			$i++;
		}
		print "\n";
		print " " if ($i < 10);
		print "$i Toggle all options ON\n"; $i++;
		print " " if ($i < 10);
		print "$i Toggle all options OFF\n"; $i++;
		print " " if ($i < 10);
		print "$i Exit\n"; $i++;
		print "\nChoice or options to toggle (applied left to right): ";
		my $ans = <STDIN>;
		my @opts = split(/ +|,/, $ans);
		foreach $ans (@opts) {
			if ($ans == scalar(@status)) { # all ON
				my $i = 0;
				while ($i < scalar(@status)) {
					$status[$i] = " ON";
					$i++;
				}
			}
			elsif ($ans == scalar(@status)+1) { # all OFF
				my $i = 0;
				while ($i < scalar(@status)) {
					$status[$i] = "OFF";
					$i++;
				}
			}
			elsif ($ans == scalar(@status)+2) { # all Exit
				$done = 1;
			} else { # toggle option
				if ($status[$ans] =~ "OFF") {
					$status[$ans] = " ON";
				} else {
					$status[$ans] = "OFF";				
				}
			}
		}
	}
		
	# write new header
	open(IN, "src-mirror/config/$header") || die "could not open $header\n";
	@file = <IN>;
	close(IN);
	open(OUT, ">src-mirror/config/$header") || die "could not open $header\n";
	my $count = -1;
	foreach my $line (@file) {
		if ($line =~ /^[\/\* ]+#define|^#define/) {
			if ($count > -1) { # skip #define at top of file
				$line = "";
				$line = $line."//" if ($status[$count] =~ "OFF");
				$line = $line."#define $symbol[$count] 1\n";
			}
			$count++;
		}
		print OUT $line;
	}
	close(OUT);
	
	# count changes
	my $changes = 0;
	my $i = 0; 
	while ($i < scalar(@status)) {
		$changes++ if ($status[$i] !~ $oldstatus[$i]);
		$i++
	}

	return $changes;
}

##############################################################################
sub print_in_columns {
	my $cols = shift(@_);
	my @choices = @_;
	
	# find longest name
	my $max_len = 0;
	my $choice;
	foreach $choice (@choices) {
		if (length($choice) > $max_len) { $max_len = length($choice); }
	}
	my $col_width = $max_len + 3 + 10; # 3 for item number and gap
	my $num_values = scalar(@choices);
	my $jump = int($num_values/($cols))+1;
	my $i = 0;
	while ($i < $jump) {
		my $line = "";
		my $col = 0;
		my $ii = $i;
		while ($col < $cols) {
			my $col_i = "";
			if ($ii < 10) { $col_i = $col_i." "; }
			if ($ii < $num_values) { $col_i = $col_i.$ii." $choices[$ii]"; }
			while ($col != $cols-1 && length($col_i) < $col_width) { $col_i = $col_i." "; }
			$col++;
			$ii += $jump;
			$line = $line.$col_i;
		}
		print "$line\n";
		$i++;
	}
}

##############################################################################
sub get_arch {
	chdir "macros"; 
	my @macros = glob("*.macros"); 
	my @choices = ();
	foreach my $choice (@macros) { 
		$choice =~ s/\.macros//; 
		push(@choices,$choice);
	}
	chdir "..";
	print "no default build architecture, choices (".scalar(@choices)."):\n";
	my $i=0;	
	print_in_columns(3, @choices);
	print "\ndefault build achitecture number: "; 
	$i = <STDIN>; 
	my $arch = $choices[$i]; 
	print "* you chose : $arch\n";
	return $arch;
}

##############################################################################
sub sort_by_depend {
	my @list_a = @_;
	my @list_b = sort by_depend @list_a;
	while (same_order(\@list_a, \@list_b) != 1) {
		@list_a = @list_b;
		@list_b = sort by_depend @list_a;
	}
	return @list_a;
}

sub same_order {
	my ($aref, $bref) = @_;
	my $i = 0;
	while ($i < scalar(@$aref)) {
		return 0 if (@$aref[$i] !~ @$bref[$i]);
		$i++;
	}
	return 1;
}

##############################################################################
sub get_missing_modules {

	# collect omitted modules
	my @allmodules = sort(keys(%module2define));
	my @missing_modules = complement(\@allmodules, \@modules);

	# collect missing, required
	@req_missing = ();
	foreach my $dir (@modules) {
		my $filename = "$dir/makefile.template";
		if (-e $filename) {
			open(IN,"$filename");
			my @lines = <IN>; $file = "@lines";
			close(IN);
			foreach my $mod (@missing_modules) {
				my $define = $module2define{$mod};
				push(@req_missing, $mod) if ($file =~ /$define/ && $file !~ /#$define/);
			}
		}
	}
	return @req_missing;
}

##############################################################################
# return the values in the first list that do not appear in the second
##############################################################################
sub complement {
	my ($all, $some) = @_;
	my @complement = ();
	foreach my $all_i (@$all) {
		my $found = 0;
		LOOK: foreach my $some_i (@$some) {
			if ($some_i =~ /^$all_i$/) {
				$found = 1;
				last LOOK;
			}
		}
		push(@complement, $all_i) if ($found == 0);
	}
	return @complement;
}

##############################################################################
sub intersection {
	my ($all, $some) = @_;
	my @complement = ();
	foreach my $all_i (@$all) {
		LOOK: foreach my $some_i (@$some) {
			if ($some_i =~ /^$all_i$/) {
				push(@complement, $all_i);
				last LOOK;
			}
		}
	}
	return @complement;
}
