#!MC 1400
# Created by Tecplot 360 build 14.0.2.35002
$!VarSet |MFBD| = ''
$!Varset |NAME| = "2d"
$!OPENLAYOUT  "|NAME|.lay"

$!EXPORTSETUP EXPORTFORMAT = PNG
$!EXPORTSETUP IMAGEWIDTH = 2000
$!EXPORTSETUP EXPORTFNAME = "|NAME|.png"
$!EXPORT
  EXPORTREGION = CURRENTFRAME

$!RemoveVar |MFBD|
