

default:
	(cd PSPASES ; make )
	(cd CPSPASES; make )
	(cd metis ; make ) 
	(cd parMetis ; make )

clean:
	(cd PSPASES ; make clean )
	(cd CPSPASES; make clean )
	(cd metis ; make clean )
	(cd parMetis ; make clean )

