/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test */

#ifndef _Included_test
#define _Included_test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test
 * Method:    Print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_Print
  (JNIEnv *, jobject);

/*
 * Class:     test
 * Method:    initCppSide
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_initCppSide
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
