/* $Id: SpherePointsT.h,v 1.1.1.1 2001-01-29 08:20:25 paklein Exp $ */
/* created: paklein (10/31/1997)                                          */
/* Base class for spherical point generators.                             */

#ifndef _SPHERE_PTS_T_H_
#define _SPHERE_PTS_T_H_

/* direct members */
#include "dArray2DT.h"
#include "dMatrixT.h"
#include "dArrayT.h"

class SpherePointsT
{
public:

	/* point generator codes (ie. the derived types) */
	enum GeneratorT {kLatLong = 0,
                 kIcosahedral = 1,
                         kFCC = 2}; // FCC lattice in shells

	/* constructor */
	SpherePointsT(void);

	/* destructor */
	~SpherePointsT(void);

	/* print parameters */
	virtual void Print(ostream& out) const = 0;
	virtual void PrintName(ostream& out) const = 0;	

	/* generate sphere points:
	 *
	 *   phi   = angle about z from x
	 *   theta = angle about x from z
	 *
	 * The final orientation is generated by applied the
	 * phi and theta rotations in succession about the local
	 * axes */
	virtual const dArray2DT& SpherePoints(double phi, double theta) = 0;

	/* list of jacobian determinants */
	const dArrayT& Jacobians(void) const;
	
protected:

	/* orient points with given rotations (in degrees) */
	void TransformPoints(double phi, double theta);
	
protected:

	/* point table */
	dArray2DT	fPoints;
	
	/* jacobians */
	dArrayT		fJacobians;

private:

	/* tranformation tensor */
	dMatrixT	fQ;
			
};

#endif /* _SPHERE_PTS_T_H_ */
