#!/usr/bin/perl -w

if (scalar(@ARGV) < 2) {
	print STDOUT "\tusage: WriteDirListMacro.pl [macro name] [output file] [0+ dir name]\n";
	exit;
}

$macro_name = shift @ARGV;
$destination = shift @ARGV;
open(OUT, ">$destination") || die "could not open output file: $destination\n";

print OUT <<FIN;
# \$Id\$
# This file was generated by WriteDirListMacro.pl
FIN
open (DATE, "date |");
while (<DATE>) {
	print OUT "# created: ".$_;
}
close(DATE);
print OUT "\n# directory list macro definition\n";
print OUT "$macro_name =";
while (@ARGV) {
	$dir = shift @ARGV;
	print OUT " \\\n\t$dir"
}
close(OUT);
