#!/usr/bin/perl -w
#------------------------------------------------------------------------------
# tahoe-manager: 
#    a PERL script to checkout, configure, build and run regression tests
#    for TAHOE
# written by: 
#    Reese Jones (rjones@sandia.gov) and Patrick Klein # (paklein@sandia.gov)
#------------------------------------------------------------------------------

# initialization
$username = getlogin();
use Cwd; # $home = cwd();
$cvsrep = "tahoe.ca.sandia.gov:/cvs/protected/tahoe"; 
%module2define = qw(
expat	EXPAT
toolbox	TB
tahoe	NODEFINE
macros	NODEFINE
);
$config_file = "./.tahoe_config";
if(-e "$config_file") { read_config();}
else                  { write_default_config();}
#print ">  architecture: $arch \n";
#print ">  modules: @modules \n";
$script_status = 0;

# loop through arguments and options
if (@ARGV < 1) {usage(); exit 0;}
ARG: while (@ARGV) {
	OPT: for (shift@ARGV) {
		$count = @ARGV;
		if ($script_status > 0 ){ failed();}
		if (/^-/) {
			if (/clean/i)             { clean(); next ARG; }
			if (/c|checkout/i)        { checkout(); next ARG; }
			if (/u|update/i)          { update(); next ARG; }
			if (/r|rebuild/i)         { rebuild(); next ARG; }
			if (/b|build/i)           { build(); next ARG; }
			if (/t|test/i)            { test(); next ARG; }
			if (/u|usage|help|h/i)           { usage();}
		}
		print "ERROR: unknown option: $_ \n"; usage();
	}
}

exit 0;

###############################################################################
sub read_config{
print "* reading config file $config_file\n";
open(CONFIG,$config_file) || die "cannot open file $config_file for reading : $!";
$type = "UNKNOWN";
while(<CONFIG>) {
	s/^\s+//; s/\s+$//; @list = split(/ +/);
 	if (defined($list[0])){
        	if (/^\#/ ){ 
			if     ($type  =~ /ARCH/){$arch = $tmp_list[0];}
 			elsif  ($type  =~ /MODU/){@modules = @tmp_list;}
 			$type = $list[1]; @tmp_list =();
 		} 
 		else { push(@tmp_list,@list);}
 	}
}
close(CONFIG);

# need to make sure the core modules exist

# need to sort modules based on dependencies
@tmp_modules = @modules;
@modules = sort by_depend @tmp_modules;
}

sub write_default_config{
print "* creating default config file $config_file\n";
# architecture
unless(-d "macros"){
	print "checking out macros\n";
	unlink("cvs.log");
	system("cvs -d $username\@$cvsrep checkout macros > cvs.log 2>&1");
}
chdir "macros"; 
@macros = glob("*.macros"); 
foreach $choice (@macros) { $choice =~ s/\.macros//; push(@choices,$choice);}
chdir "..";
print "no default build architecture, choices:\n";
$i=0;foreach $choice (@choices) { print "$i $choice\n"; $i++;}
print "? "; $i = <STDIN>; $arch = $choices[$i]; 
print "* you chose : $arch\n";
# modules
@modules = ("macros","expat","toolbox","tahoe");
open(CONFIG,">$config_file") || die "cannot open file $config_file for writing : $!";
print CONFIG  "# ARCHITECTURE\n$arch\n\n";
print CONFIG  "# MODULES\n@modules\n\n";
print CONFIG  "# EOF";
close(CONFIG);
}

sub checkout{
	$time = localtime();
	print "($count) checking out: @modules, at $time\n";
	unlink("cvs.log");
	system("cvs -d $username\@$cvsrep checkout @modules > cvs.log 2>&1");
}

sub update{
	$time = localtime();
	print "($count) updating: @modules, at $time\n";
	unlink("cvs.log");
	foreach $dir (@modules) {
		system("cd $dir; cvs update -Pd > ../cvs.log 2>&1");
	}
}

sub rebuild{
	$time = localtime();
	print "($count) rebuilding: @modules, at $time\n";
# winnow out "static" modules??
	foreach $dir (@modules) {
		chdir $dir;
		if (-e "makefile" && !(-e "static")) {
			unlink("build.log");
			system("make build > build.log 2>&1");
		# check build log for errors	
		}
		chdir "..";
	}
}

sub build{
	$time = localtime();
	print "($count) building: @modules, at $time\n";
	foreach $dir (@modules) {
		chdir $dir;
		if (-e "makefile.template") {
			fillin_makefile();
			unlink("build.log");
			system("make init build > build.log 2>&1");
			
		}
		chdir "..";
	}
}

sub test{
	$time = localtime();
	print "($count) running tests at $time\n";
 	unless(-d "benchmark"){
		print "checking out benchmark\n";
		unlink("cvs.log");
		system("cvs -d $username\@$cvsrep checkout benchmark > cvs.log 2>&1");
 	} else {
		system("cd benchmark; cvs update -Pd > cvs.log 2>&1");
	}
	chdir("benchmark/comparator");
	fillin_makefile(); system("make init build > build.log 2>&1");
	chdir("..");
	#print("running benchmarks\n");
	system("../tahoe/tahoe -f run.batch > run.out 2>&1");
	#print("comparing benchmarks\n");
	system("./comparator/compare -f run.batch > compare.out 2>&1");
	open(IN,"compare.summary");
	<IN>; 
	$_ = <IN>; chomp(); s/^\s+//; s/\s+$//; $pass = $_;   
	$_ = <IN>; chomp(); s/^\s+//; s/\s+$//; $fail = $_;   
	# $path = cwd();
	print "$pass $fail, see compare.summary for more details\n";
}

sub clean{
	$time = localtime();
	print "($count) cleaning: @modules, at $time\n";
	foreach $dir (@modules) {
		chdir $dir; 
		system("rm -rf src-mirror obj object_list");
		chdir ".."; 
	}
}

sub failed{
	$time = localtime();
	die "*-*-*-* process FAILED at $time *-*-*-*\n";
}

sub usage{
	print "\nusage: tahoe-manager [list of keywords and options]\n";
	print "       checkout: checks out\n";
	print "       update  : updates\n";
	print "       build   : builds \n";
	print "       rebuild : rebuilds \n";
	print "       test    : runs regression tests\n";
	print "       clean   : cleans \n";
	exit 1;
}

sub by_depend {
	$filename = "$a/makefile.template";
	if (-e $filename) {
		open(IN,"$filename");
		@lines = <IN>; $afile = "@lines"; 
		close(IN);
		$bdefine = $module2define{$b}; 
 		$a_on_b = ($afile =~ /$bdefine/);
		unless(defined($a_on_b)) {$a_on_b = 0;}
	} else { $a_on_b = -1;}

	$filename = "$b/makefile.template";
	if (-e $filename) {
		open(IN,"$filename");
		@lines = <IN>; $bfile = "@lines"; 
		close(IN);
		$adefine = $module2define{$a};
	        $b_on_a = ($bfile =~ /$adefine/);
		unless(defined($b_on_a)) {$b_on_a = 0;}
	} else { $b_on_a = -1;};

        ($a_on_b <=> $b_on_a);
}

sub fillin_makefile{
	unlink("makefile");
	$path = cwd();
	open(IN,"makefile.template");
	open(OUT,">makefile");
	while (defined($line = <IN>)){
		$line =~ s/HOME_DIR =/HOME_DIR = $path/;
		$line =~ s/ARCH =/ARCH = $arch/;
		print OUT "$line";
 	}
	close(IN);
	close(OUT);
}

