#!/usr/bin/perl -w
#------------------------------------------------------------------------------
# tahoe-manager: 
#    a PERL script to checkout, configure, build and run regression tests
#    for TAHOE
# written by: 
#    Reese Jones (rjones@sandia.gov) and Patrick Klein # (paklein@sandia.gov)
#------------------------------------------------------------------------------

# initialization
$username = getlogin();
use Cwd; # $home = cwd();
$cvsrep = "tahoe.ca.sandia.gov:/cvs/protected/tahoe"; 
%module2define = qw(
expat	EXPAT_
toolbox	TB_
tahoe	NODEFINE
macros	NODEFINE
spooles SPOOLES_
f2c	F2C_
blas	BLAS_
);
$config_file = "./.tahoe_config";
if(-e "$config_file") { read_config();}
else                  { write_default_config();}
print "> architecture: $arch \n"; 
$script_status = 0;

# loop through arguments and options
if (@ARGV < 1) {usage(); exit 0;}
ARG: while (@ARGV) {
	OPT: for (shift@ARGV) {
		$count = @ARGV;
		if ($script_status > 0 )   { failed();}
		if (/^u|update/i)          { update(); next ARG; }
		if (/^r|rebuild/i)         { rebuild(); next ARG; }
		if (/^b|build/i)           { build(); next ARG; }
		if (/^t|test/i)            { test(); next ARG; }
		if (/^u|usage|help|^h/i)   { usage();}
		print "ERROR: unknown option: $_ \n"; usage();
	}
}

exit 0;

###############################################################################
sub read_config{
print "* reading config file $config_file\n";
open(CONFIG,$config_file) || die "cannot open file $config_file for reading : $!";
$type = "UNKNOWN";
while(<CONFIG>) {
	s/^\s+//; s/\s+$//; @list = split(/ +/);
 	if (defined($list[0])){
        	if (/^\#/ ){ 
			if     ($type  =~ /ARCH/){$arch = $tmp_list[0];}
 			elsif  ($type  =~ /MODU/){@modules = @tmp_list;}
 			$type = $list[1]; @tmp_list =();
 		} 
 		else { push(@tmp_list,@list);}
 	}
}
close(CONFIG);

# need to make sure the core modules exist

# need to sort modules based on dependencies
@tmp_modules = @modules;
@modules = sort by_depend @tmp_modules;
}

sub write_default_config{
print "* creating default config file $config_file\n";
# architecture
unless(-d "macros"){
	print "checking out macros\n";
	unlink("cvs.log");
	system("cvs -d $username\@$cvsrep checkout macros > cvs.log 2>&1");
}
chdir "macros"; 
@macros = glob("*.macros"); 
foreach $choice (@macros) { $choice =~ s/\.macros//; push(@choices,$choice);}
chdir "..";
print "no default build architecture, choices:\n";
$i=0;foreach $choice (@choices) { print "$i $choice\n"; $i++;}
print "? "; $i = <STDIN>; $arch = $choices[$i]; 
print "* you chose : $arch\n";
# modules
@modules = ("macros","expat","toolbox","tahoe");
open(CONFIG,">$config_file") || die "cannot open file $config_file for writing : $!";
print CONFIG  "# ARCHITECTURE\n$arch\n\n";
print CONFIG  "# MODULES\n@modules\n\n";
print CONFIG  "# EOF";
close(CONFIG);
}

sub update{
	$time = localtime();
	print "($count) updating: @modules, at $time\n";
	unlink("cvs.log");
	foreach $dir (@modules) {
		if(-d $dir) {
			print "\tupdating $dir";
			system("cd $dir; cvs update -Pd > ../cvs.log 2>&1");
			print " ...done\n";
		} else {
			print "\tchecking out $dir";
			system("cvs -d $username\@$cvsrep checkout $dir > cvs.log 2>&1");
			print " ...done\n";
		}
		# check for failures
		open(IN,"cvs.log");
		@lines = <IN>; $file = "@lines"; close(IN); 
		$errors = ($file =~ /^C /);
                if($errors > 0) {$script_status++;}
	}
}

sub rebuild{
	$time = localtime();
	print "($count) rebuilding: @modules, at $time\n";
# winnow out "static" modules??
	foreach $dir (@modules) {
		chdir $dir;
		if (-e "makefile") {
			print "\tmaking $dir";
			unlink("build.log");
			system("make build > build.log 2>&1");
			# check for errors	
			open(IN,"build.log");
			@lines = <IN>; $file = "@lines"; close(IN); 
			$errors = ($file =~ / error /i);
                	if($errors > 0) {print " ...ERROR\n";$script_status++;}
			else            {print " ...done\n";}
		}
		chdir "..";
	}
}

sub build{
	$time = localtime();
	print "($count) building: @modules, at $time\n";
	foreach $dir (@modules) {
		chdir $dir;
		if (-e "makefile.template") {
			fillin_makefile();
			print "\tmaking $dir";
			unlink("build.log");
			system("rm -rf src-mirror obj object_list");
			system("make init build > build.log 2>&1");
			print " ...done\n";
			# check for errors	
			open(IN,"build.log");
			@lines = <IN>; $file = "@lines"; close(IN); 
			$errors = ($file =~ / error /i);
                	if($errors > 0) {print " ...ERROR\n";$script_status++;}
			else            {print " ...done\n";}
		}
		chdir "..";
	}
}

sub test{
	$time = localtime();
	print "($count) running tests at $time\n";
 	unless(-d "benchmark"){
		print "checking out benchmark\n";
		unlink("cvs.log");
		system("cvs -d $username\@$cvsrep checkout benchmark > cvs.log 2>&1");
 	} else {
		system("cd benchmark; cvs update -Pd > cvs.log 2>&1");
	}
	chdir("benchmark/comparator");
	print("\tbuilding comparator");
	fillin_makefile(); system("make init build > build.log 2>&1");
	print(" ...done\n");
	chdir("..");
	print("\trunning benchmarks");
	system("../tahoe/tahoe -f run.batch > run.out 2>&1");
	print(" ...done\n");
	print("\tcomparing benchmarks");
	system("./comparator/compare -f run.batch > compare.out 2>&1");
	print(" ...done\n");
	open(IN,"compare.summary");
	<IN>; 
	$_ = <IN>; chomp(); s/^\s+//; s/\s+$//; $pass = $_;   
	$_ = <IN>; chomp(); s/^\s+//; s/\s+$//; $fail = $_;   
	print "* $pass $fail, see compare.summary for more details\n";
}

sub failed{
	$time = localtime();
	die "*-*-*-* process FAILED at $time *-*-*-*\n";
}

sub usage{
	print "\nusage: tahoe-manager [list of keywords and options]\n";
	print "       update  : updates or checks out modules\n";
	print "       build   : builds modules \n";
	print "       rebuild : rebuilds modules \n";
	print "       test    : runs regression tests\n";
	exit 1;
}

sub by_depend {
	$filename = "$a/makefile.template";
	$a_on_b = -1;
	if (-e $filename) {
		open(IN,"$filename");
		@lines = <IN>; $afile = "@lines"; 
		close(IN);
		$bdefine = $module2define{$b}; 
 		$a_on_b = ($afile =~ /$bdefine/);
		unless($a_on_b > 0) {$a_on_b = 0;}
	}

	$filename = "$b/makefile.template";
	$b_on_a = -1;
	if (-e $filename) {
		open(IN,"$filename");
		@lines = <IN>; $bfile = "@lines"; 
		close(IN);
		$adefine = $module2define{$a};
	        $b_on_a = ($bfile =~ /$adefine/);
		unless($b_on_a > 0) {$b_on_a = 0;}
	}

	#print " $a $a_on_b $b $b_on_a \n";

        ($a_on_b <=> $b_on_a);
}

sub fillin_makefile{
	unlink("makefile");
	$path = cwd();
	open(IN,"makefile.template");
	open(OUT,">makefile");
	while (defined($line = <IN>)){
		$line =~ s/HOME_DIR =/HOME_DIR = $path/;
		$line =~ s/ARCH =/ARCH = $arch/;
		foreach $module (@modules) {
			$define = $module2define{$module};
			$line =~ s/\#$define/$define/;
		}
		print OUT "$line";
 	}
	close(IN);
	close(OUT);
}

