/* $Id: FieldT.h,v 1.6 2002-11-28 16:44:19 paklein Exp $ */

#ifndef _FIELD_T_H_
#define _FIELD_T_H_

/* base class */
#include "BasicFieldT.h"

/* direct members */
#include "iArrayT.h"
#include "dArrayT.h"
#include "IC_CardT.h"
#include "KBC_CardT.h"
#include "FBC_CardT.h"
#include "pArrayT.h"
#include "GlobalT.h"
#include "AutoArrayT.h"

namespace Tahoe {

/* forward declarations */
class LocalArrayT;
class nControllerT;
class KBC_ControllerT;
class FBC_ControllerT;
template <class TYPE> class RaggedArray2DT;
class ifstreamT;
class ofstreamT;
class FieldSupportT;

/** field with time integration. Includes application of initial and 
 * boundary conditions, and force boundary conditions. */
class FieldT: public BasicFieldT
{
public:

	/** inactive equation number codes */
	enum EquationCodeT {
	          kInit = 0, /**< uninitialized equation number */
		kPrescribed =-1, /**< dof has prescribed value */ 
	      kExternal =-2  /**< node is external */ };

	/** constructor */
	FieldT(const StringT& name, int ndof, nControllerT& controller);
	
	/** destructor */
	~FieldT(void);

	/** \name initialization */
	/*@{*/
	/** register the local array with its source */
	void RegisterLocal(LocalArrayT& array) const;

	/** set the group number */
	void SetGroup(int group) { fGroup = group; };

	/** set number of nodes. (Re-)allocates memory. */
	void Dimension(int nnd);	
	/*@}*/
	
	/** \name accessors */
	/*@{*/
	/** set the group number */
	int Group(void) const { return fGroup; };	
	
	/** time integrator */
	nControllerT& nController(void) const { return fnController; };

	/** append connectivities generated by the KBC_ControllerT's and
	 * FBC_ControllerT's. */
	void Connectivities(AutoArrayT<const iArray2DT*>& connects_1,
		AutoArrayT<const RaggedArray2DT<int>*>& connects_2) const;

	/** return the GlobalT::SystemTypeT for the all the fields in the
	 * specified group */
	GlobalT::SystemTypeT SystemType(void) const;

	/** initial condition cards */
	ArrayT<IC_CardT>& InitialConditions(void) { return fIC; };
	
	/** kinematic boundary condition cards */
	ArrayT<KBC_CardT>& KinematicBC(void) { return fKBC; };

	/** prescribed nodal forces */
	ArrayT<FBC_CardT>& ForceBC(void) { return fFBC; };

	/** special kinematic boundary conditions. Controllers put in this array
	 * are deleted when this field goes out of scope. */
	pArrayT<KBC_ControllerT*>& KBC_Controllers(void) { return fKBC_Controllers; };

	/** special force boundary conditions. Controllers put in this array
	 * are deleted when this field goes out of scope. */
	pArrayT<FBC_ControllerT*>& FBC_Controllers(void) { return fFBC_Controllers; };
	/*@}*/

	/** \name time integration */
	/*@{*/
	/** beginning of time series */
	void InitialCondition(void);
	
	/** apply predictor to all degrees of freedom */
	void InitStep(void);

	/** \name form tangent and force contributions */
	/*@{*/
	/** compute LHS-side matrix and assemble to solver.
	 * \param support host information
	 * \param sys_type "maximum" LHS matrix type needed by the solver. The GlobalT::SystemTypeT
	 *        enum is ordered by generality. The solver should indicate the most general
	 *        system type that is actually needed. */
	void FormLHS(const FieldSupportT& support, GlobalT::SystemTypeT sys_type);

	/** compute RHS-side, residual force vector and assemble to solver
	 * \param support host information */
	void FormRHS(const FieldSupportT& support);
	/*@}*/

	/** update the active degrees of freedom */
	void Update(const dArrayT& update, int eq_start, int num_eq);
	
	/** check for relaxation */
	GlobalT::RelaxCodeT RelaxSystem(void);

	/** update history */
	void CloseStep(void);

	/** reset displacements (and configuration to the last known solution) */
	void ResetStep(void);
	/*@}*/

	/** \name equation numbers */
	/*@{*/
	/** initialize an equations array. The array is dimensioned for the number
	 * of nodes and dof's. Prescribed equations are marked FieldT::kPrescribed. All 
	 * others are marked FieldT::kInit. Prescribed values are marked first
	 * using the nodally prescribed kinematic boundary conditions
	 * followed by the KBC_ControllerT's. Equation numbers for prescribed
	 * values will be < 0. */
	void InitEquations(iArray2DT& eqnos);

	/** set the equations array and the number of active equations */
	void SetEquations(iArray2DT& eqnos, int num_active);

	/** dimension storage and mark equation numbers for external nodes */
	void InitExternalEquations(const iArrayT& ex_nodes);
	
	/** the number of equations for the field */
	int NumActiveEquations(void) const { return fNumActiveEquations; };

	/** append the equation sets generated by the field. These include sets
	 * generated by the KBC_ControllerT's and FBC_ControllerT's. This call
	 * signals to the field that FieldT::Equations has been filled with
	 * up to date equation numbers. */
	void EquationSets(AutoArrayT<const iArray2DT*>& eq_1, 
		AutoArrayT<const RaggedArray2DT<int>*>& eq_2);

	/** collect equation numbers.
	 * \param nodes element connectivities: [nel] x [nen]
	 * \param eqnos destination for equation numbers: [nel] x [nen*ndof] */
	void SetLocalEqnos(const iArray2DT& nodes, iArray2DT& eqnos) const;
	
	/** collect equation numbers.
	 * \param nodes element connectivities: [ngr] x [nel_i] x [nen]
	 * \param eqnos destination for equation numbers: [nel_0 + nel_1 + ...] x [nen*ndof] */
	void SetLocalEqnos(ArrayT<const iArray2DT*> nodes, iArray2DT& eqnos) const;

	/** collect equation numbers. Connectivities are passed in a RaggedArray2DT, 
	 * which allows an arbitrary number of nodes per element.
	 * \param nodes element connectivities: [nel] x [nen_i]
	 * \param eqnos destination for equation numbers: [nel] x [nen_i*ndof] */
	void SetLocalEqnos(const RaggedArray2DT<int>& nodes, RaggedArray2DT<int>& eqnos) const;

	/** collect equation numbers */
	void SetLocalEqnos(const iArrayT& tags, iArray2DT& eqnos) const;
	/*@}*/

	/** \name restart functions
	 * The restart functions should read/write any data that overrides the
	 * default values */
	/*@{*/ 
	void ReadRestart(ifstreamT& in);
	void WriteRestart(ofstreamT& out) const;
	/*@}*/ 

	/** write output data */
	void WriteOutput(ostream& out) const;

	/** write field parameters to output stream */
	void WriteParameters(ostream& out) const;
	
	/** \name "ghost" node data */
	/*@{*/
	/** active/prescribed flags for "ghost" nodes */
	iArray2DT& ExternalEquations(void) { return fExEqnos; };

	/** space for the update for "ghost" nodes */
	dArray2DT& ExternalUpdate(void) { return fExUpdate; };
	/*@}*/

	/** \name source terms 
	 * Support multiple sources to the same block ID. The current
	 * implementation assumes the contributors of source terms have
	 * the same time increment as the users of the sources. That is,
	 * the most recently calculated values in the source arrays are
	 * assumed to be up to date. There is no separate accumulation
	 * for sub-steps. 
	 * \note Could add some information about the interval. This
	 *       would allow contributors to decide whether or not
	 *       source terms need to be accumulated or overwritten. */
	/*@{*/
	/** register an array as source. Owner is responsible for keeping the
	 * source array up to date. No assumptions are made on how many times
	 * the same source array can be registered. Arrays registered more
	 * that once will contribute more than once. */
	void RegisterSource(const StringT& ID, const dArray2DT& source) const;
	
	/** element source terms. return a pointer to the source terms for the 
	 * given element block ID, or NULL if no source terms exist for that
	 * block. This accumulates all source contributions to the given
	 * block ID. */
	const dArray2DT* Source(const StringT& ID) const;
	/*@}*/

private:

	/** apply the IC_CardT to the field */
	void Apply_IC(const IC_CardT& card);

	/** mark global equations with the specified BC */
	void SetBCCode(const KBC_CardT& card);

	/** determine the destinations for the force boundary conditions */
	void SetFBCEquations(void);

	/** return the index for the source of the given ID. Returns -1 if
	 * if no source exists for given ID */
	int SourceIndex(const StringT& ID) const;

private:

	/** solution set number */
	int fGroup;

	/** time integrator */
	nControllerT& fnController;

	/** the number of active equations. This is the number of unique equation
	 * numbers in the active range for this processor. This count is passed in
	 * during the call to */
	int fNumActiveEquations;
	
	/** field history. BasicFieldT::fField from the previous time step. */
	ArrayT<dArray2DT> fField_last;
	
	/** \name initial and kinematic boundary conditions */
	/*@{*/
	/** initial conditions */
	ArrayT<IC_CardT> fIC;
	  	
	/** kinematic boundary conditions */
	ArrayT<KBC_CardT> fKBC;

	/** special KBC objects */
	pArrayT<KBC_ControllerT*> fKBC_Controllers;
	/*@}*/

	/** \name force boundary conditions */
	/*@{*/
	/** nodal forces */
	ArrayT<FBC_CardT> fFBC;

	/** force vector */
	dArrayT fFBCValues;

	/** equations with applied forces */
	iArrayT fFBCEqnos;

	/** special FBC objects */
	pArrayT<FBC_ControllerT*> fFBC_Controllers;
	/*@}*/
	
	/** \name "ghost" node work space */
	/*@{*/
	/** free/prescribed ghost node equations */
	iArray2DT fExEqnos;	

	/** communication buffer */
	dArray2DT fExUpdate;
	/*@}*/
	
	/** \name source terms */
	/*@{*/
	/** ID's for the elements blocks in fSource. This array is
	 * a union of the ID's in FieldT::fSourceID. */
	AutoArrayT<StringT> fID;

	/** return values for sources. When FieldT::Source is called, all
	 * contributions to the given block are accumulated and passed back.
	 * Each entry is: [nen] x [nip*nval] */
	AutoArrayT<dArray2DT*> fSourceOutput;
	
	/** ID's for the sources registerered with FieldT::RegisterSource */
	AutoArrayT<StringT> fSourceID;
	
	/** block source terms registerered with FieldT::RegisterSource.
	 * Each entry is: [nen] x [nip*nval] */
	AutoArrayT<const dArray2DT*> fSourceBlocks;
	/*@}*/
};

/* inlines */
inline void FieldT::SetLocalEqnos(const iArrayT& tags,
	iArray2DT& eqnos) const
{
	eqnos.RowCollect(tags,fEqnos);
}

} // namespace Tahoe 
#endif /* _FIELD_T_H_ */
