FILE1=plot
FILE2=plotvec
FILE3=plot1pc
FILE4=plot1pp
FILE5=probedual
FILE6=probe1p
FILE7=plotmz
FILE8=plotsec
FILE9=plotpile
FILE10=plotsecpile
FILE11=initfree
all: $(FILE1) $(FILE2) $(FILE3) $(FILE4) $(FILE5) $(FILE6) $(FILE7) $(FILE8) $(FILE9) $(FILE10) $(FILE11)
$(FILE1): $(FILE1).cpp
	g++ -Wall -gstabs -o $(FILE1) $(FILE1).cpp
$(FILE2): $(FILE2).cpp
	g++ -Wall -gstabs -o $(FILE2) $(FILE2).cpp
$(FILE3): $(FILE3).cpp
	g++ -Wall -gstabs -o $(FILE3) $(FILE3).cpp
$(FILE4): $(FILE4).cpp
	g++ -Wall -gstabs -o $(FILE4) $(FILE4).cpp
$(FILE5): $(FILE5).cpp
	g++ -Wall -gstabs -o $(FILE5) $(FILE5).cpp
$(FILE6): $(FILE6).cpp
	g++ -Wall -gstabs -o $(FILE6) $(FILE6).cpp
$(FILE7): $(FILE7).cpp
	g++ -Wall -gstabs -o $(FILE7) $(FILE7).cpp
$(FILE8): $(FILE8).cpp
	g++ -Wall -gstabs -o $(FILE8) $(FILE8).cpp
$(FILE9): $(FILE9).cpp
	g++ -Wall -gstabs -o $(FILE9) $(FILE9).cpp
$(FILE10): $(FILE10).cpp
	g++ -Wall -gstabs -o $(FILE10) $(FILE10).cpp
	g++ -Wall -gstabs -o $(FILE9) $(FILE9).cpp
$(FILE11): $(FILE11).cpp
	g++ -Wall -gstabs -o $(FILE11) $(FILE11).cpp
