#!MC 1000
$!VarSet |MFBD| = ''
$!FIELDMAP [1]  SURFACES{SURFACESTOPLOT = EXPOSEDCELLFACES}
$!FIELDLAYERS SHOWMESH = YES
$!FIELDLAYERS SHOWEDGE = NO
$!REDRAWALL 
$!FIELDMAP [1-100]  MESH{COLOR = GREEN}
$!FIELDMAP [1-100]  MESH{LINETHICKNESS = 0.4}
$!FIELDMAP [1-100]  SHADE{SHOW = NO}
$!FIELDMAP [1-100]  SURFACES{SURFACESTOPLOT = EXPOSEDCELLFACES}
$!REDRAWALL 
$!VIEW SETMAGNIFICATION
  MAGNIFICATION = 1
$!RemoveVar |MFBD|
