/* $Id: IcosahedralPtsT.h,v 1.1.1.1 2001-01-29 08:20:25 paklein Exp $ */
/* created: paklein (10/31/1997)                                          */
/* Base class for spherical point generators.                             */

#ifndef _ICO_PTS_T_H_
#define _ICO_PTS_T_H_

/* base class */
#include "SpherePointsT.h"

/* forward declarations */
class ifstreamT;

class IcosahedralPtsT: public SpherePointsT
{
public:

	/*
	 * Constructor
	 */
	IcosahedralPtsT(ifstreamT& in);

	/*
	 * Print parameters.
	 */
	virtual void Print(ostream& out) const;
	virtual void PrintName(ostream& out) const;	

	/*
	 * Generate sphere points:
	 *
	 *   phi   = angle about z from x
	 *   theta = angle about x from z
	 *
	 * The final orientation is generated by applied the
	 * phi and theta rotations in succession about the local
	 * axes.
	 *
	 */
	virtual const dArray2DT& SpherePoints(double phi, double theta);

private:

	/* set data pointer for the specified number of integration points */
	void SetCoords(int numint);
	void SetJacobians(int numint);

private:

	/* parameters */
	int	fN;
			
};

#endif /* _ICO_PTS_T_H_ */
